### PR TITLE
Release v0.5.11

### PR DESCRIPTION
**Pull request by AlexisRenchon**
Release v0.5.11

### CODE REVIEW

**Comment by Sbozzolo** [comment]
@ph-kev has a couple more PRs that would be good to get in before making a new release. 

Do you need this new release soon?

**Comment by AlexisRenchon** [comment]
No rush!

**Comment by ph-kev** [comment]
We can make a new release for ClimaAnalysis.

**Comment by AlexisRenchon** [comment]
@Sbozzolo  I am happy to do it if you confirm this is ok

**Comment by Sbozzolo** [comment]
Yes, I was waiting for @ph-kev. Feel free to go ahead.

**Pull request merged**
